config/routes.rb
Rails.application.routes.draw do
  resources :ad_requests do
     member do
        get :delete
     end
 end
get 'ad_request/index'
  resources :message_boards
  get 'category/sports'

  get 'category/food'

  get 'category/study'

  get 'about_us/site_info'

  get 'about_us/contact'

  get 'about_us/FAQ'

  get 'sessions/new'

  resources :groups
  resources :users
  resources :widgets
  get  '/signup',  to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  root 'welcome#index'
  match ':controller(/:action(/:id))', :via=>[:get, :post]

end

app/models/message_board.rb
class MessageBoard < ActiveRecord::Base
  belongs_to :user
  validates :sender, presence: true
  validates :user_id, presence: true
  validates :group_name, presence: true
  validates :message, presence: true, length: {maximum: 200 }
end

app/controllers/message_boards_controller.rb
class MessageBoardsController < ApplicationController
  before_action :set_message_board, only: [:show, :edit, :update, :destroy]

  # GET /message_boards
  # GET /message_boards.json
  def index
    @message_boards = MessageBoard.all
  end

  # GET /message_boards/1
  # GET /message_boards/1.json
  def show
  end

  # GET /message_boards/new
  def new
    @message_board = MessageBoard.new
    @groups=Group.all
  end

  # GET /message_boards/1/edit
  def edit
  end

  # POST /message_boards
  # POST /message_boards.json
  def create
    @message_board = MessageBoard.new(message_board_params)
    @groups=Group.all
    respond_to do |format|
      if @message_board.save
        format.html { redirect_to @message_board, notice: 'Message board was successfully created.' }
        format.json { render :show, status: :created, location: @message_board }
      else
        format.html { render :new }
        format.json { render json: @message_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /message_boards/1
  # PATCH/PUT /message_boards/1.json
  def update
    respond_to do |format|
      if @message_board.update(message_board_params)
        format.html { redirect_to @message_board, notice: 'Message board was successfully updated.' }
        format.json { render :show, status: :ok, location: @message_board }
      else
        format.html { render :edit }
        format.json { render json: @message_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /message_boards/1
  # DELETE /message_boards/1.json
  def destroy
    @message_board.destroy
    respond_to do |format|
      format.html { redirect_to message_boards_url, notice: 'Message board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message_board
      @message_board = MessageBoard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_board_params
      params.require(:message_board).permit(:sender, :group_name, :message, :user_id)
    end
end

app/helpers/message_boards_helper.rb
module MessageBoardsHelper
end

app/views/message_boards/_form.html.erb
<%if logged_in?%>
  <%= form_for(@message_board) do |f| %>
    <% if @message_board.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@message_board.errors.count, "error") %> prohibited this message from being saved:</h2>
        <% @message_board.errors.full_messages.each do |message| %>
          <p style="text-align:left;"><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <div class="field">
      <% fullname=loggedin_user.first_name+ " "+loggedin_user.last_name%>
      <%= f.hidden_field :sender, :value => fullname%>
      <%= f.hidden_field :user_id, :value => loggedin_user.id%>
    </div>
    <%tem=[]%>
    <% @groups.each do |group| %>
      <%tem.push(group.name)%>
    <%end%>
    <div class="field">
      <%= f.label :Which_group_are_you_sending_to? %><br>
      <%= f.select :group_name ,tem, :required=> 'r'%>
    </div>
    <div class="field">
      <%= f.label :message %><br>
      <%= f.text_area :message, :required=>'r', rows: "5", cols: "35"%>
    </div>
    <div class="actions">
      <%= f.submit "Create message"%>
    </div>
  <% end %>
<%end%>

app/views/message_boards/_form2.html.erb
<%if logged_in?%>
    <%= form_for(@message_board) do |f| %>
      <% if @message_board.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@message_board.errors.count, "error") %> prohibited this message from being saved:</h2>
          <% @message_board.errors.full_messages.each do |message| %>
          <p style="text-align:left;"><%= message %></p>
          <% end %>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :message %><br>
        <%= f.text_area :message, :required=>'r', rows: "5", cols: "35"%>
      </div>
      <div class="actions">
        <%= f.submit "Update message" %>
      </div>
    <% end %>
<%end%>

app/views/message_boards/edit.html.erb
<% @page_title = "Message-Edit" %>


<div class="MessageEdit container">
  <div class="row">
    <div class="col-sm-12">
		<%if logged_in?%>
		  <%if loggedin_user.id==@message_board.user_id || loggedin_user.admin? %>
		    <legend><h1>Editing Message</h1></legend>

		    <%= render 'form2' %>

		    <%= link_to 'Back', message_boards_path, { :class => "btn btn-primary"} %>
		  <%else%>
		    <p style="color:red;font-size:200%;"> You do not have access to edit this message</p>
		  <%end%>
		<%else%>
		  <p style="color:red;font-size:200%;"> Please log in before editing message</p>
		<%end%>
      <br><br>

    </div>
  </div>  <!-- end row -->
</div><!-- end MessageCreate container -->

app/views/message_boards/index.html.erb
<% @page_title = "Message" %>


<div class="Message container">
  <div class="row">
    <div class="col-sm-12">
      <h1>ALL Messages</h1>

      <%= link_to 'New Message', new_message_board_path, :class => "btn btn-primary" %>
      <br>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Sender</th>
            <th>for group</th>
            <th>Message</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @message_boards.each do |message_board| %>
            <tr>
              <td><%= message_board.sender %></td>
              <td><%= message_board.group_name %></td>
              <td><%= message_board.message %></td>
              <td><%= link_to 'Show', message_board, { :class => "btn btn-info"} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      
      <br><br>

    </div>
  </div>  <!-- end row -->
</div><!-- end Message container -->

app/views/message_boards/new.html.erb
<% @page_title = "Message-Create" %>


<div class="MessageCreate container">
  <div class="row">
    <div class="col-sm-12">
	<% if logged_in? %>
	  <legend><h1>New Message</h1></legend>
	  <%= render 'form' %>

	  <%= link_to 'Back', message_boards_path,  { :class => "btn btn-primary"} %>
	  <% else %>
	  <p style="color:red;font-size:200%;"> Please log in before creating  message</p>
	<%end%>

      
      <br><br>

    </div>
  </div>  <!-- end row -->
</div><!-- end MessageCreate container -->

app/views/message_boards/show.html.erb
<% @page_title = "Message-show" %>


<div class="MessageShow container">
  <div class="row">
    <div class="well col-sm-12">
      <p>
        <strong>Sender:</strong>
        <%= @message_board.sender %>
      </p>

      <p>
        <strong>for_group:</strong>
        <%= @message_board.group_name %>
      </p>

      <p>
        <strong>Message:</strong>
        <%= @message_board.message %>
      </p>

      <%= link_to 'Back', message_boards_path, { :class => "btn btn-primary"} %>

      <%if logged_in?%>
        <%if loggedin_user.id==@message_board.user_id || loggedin_user.admin?%>
          <%= link_to 'Edit', edit_message_board_path(@message_board), { :class => "btn btn-info"} %> 
          <%= link_to 'Destroy', @message_board, method: :delete,  :class => "btn btn-danger", data: { confirm: 'Are you sure?' } %>
        <%end%>
      <%end%>

      
      <br><br>

    </div>
  </div>  <!-- end row -->
</div><!-- end MessageSHow container -->