config/routes.rb
Rails.application.routes.draw do
  resources :ad_requests do
     member do
        get :delete
     end
 end
get 'ad_request/index'
  resources :message_boards
  get 'category/sports'

  get 'category/food'

  get 'category/study'

  get 'about_us/site_info'

  get 'about_us/contact'

  get 'about_us/FAQ'

  get 'sessions/new'

  resources :groups
  resources :users
  resources :widgets
  get  '/signup',  to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  root 'welcome#index'
  match ':controller(/:action(/:id))', :via=>[:get, :post]

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  validates :name, uniqueness: {case_sensitive: false}, presence: true, length: {maximum: 50 }
  validates :time, presence: true
  validates :activity_type, presence: true
  validates :location, presence: true, length: {maximum: 50 }
  validates :group_owner, presence: true
  validates :description, presence: true, length: {maximum: 500 }
  # validate :event_time_should_be_later_than_now
  # def event_time_should_be_later_than_now
  #   if time<Time.now
  #     errors.add(:time, "time is invalid(should be later than present time)")
  #   end
  # end
  #calculate longitude & latitude
  geocoded_by :location
  after_validation :geocode

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @user=User.all
    @message_board=MessageBoard.all
    @hash = Gmaps4rails.build_markers(@group) do |group, marker|
    marker.lat group.latitude
    marker.lng group.longitude
    marker.infowindow "here is the location"
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id=loggedin_user.id
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PATCH/PUT /groups/1
  # # PATCH/PUT /groups/1.json
  # def join
  #   if logged_in?
  #   @group.member1=loggedin_user.first_name
  #   respond_to do |format|
  #     if @group.update(group_params)
  #       format.html { redirect_to @group, notice: 'successfully join the group' }
  #       format.json { render :show, status: :ok, location: @group }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @group.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  # end
  #
  # # PATCH/PUT /groups/1
  # # PATCH/PUT /groups/1.json
  # def quit
  #   respond_to do |format|
  #     if @group.update(group_params)
  #       format.html { redirect_to @group, notice: 'successfully quit the group.' }
  #       format.json { render :show, status: :ok, location: @group }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @group.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :time, :activity_type, :location, :group_owner, :member1, :member2, :member3, :member4, :description,:user_id, :member1id, :member2id, :member3id, :member4id, :latitude, :longitude)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<% if logged_in? %>
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <% @group.errors.full_messages.each do |message| %>
        <p style="text-align:left;"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= f.label :name, :class => "col-sm-2 control-label", :for =>"inputName" %>
      <div class="col-sm-10">
        <%= f.text_field :name, :required=>'r',:class => "form-control", :id => "inputName" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :time, :class => "col-sm-2 control-label", :for =>"inputTime" %>
      <div class="col-sm-10">
        <%= f.datetime_select :time, :class => "form-control", :id => "inputTime"  %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :activity_type, :class => "col-sm-2 control-label", :for =>"inputGroupType"  %>
      <div class="col-sm-10">
        <%= f.select :activity_type ,["sports", "food", "study"], :required=> 'r', :id => "inputGroupType"%>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :location, :class => "col-sm-2 control-label", :for =>"inputLocation"  %>
      <div class="col-sm-10">
        <%= f.text_field :location, :required=>'r', :class => "form-control", :id => "inputLocation" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <% fullname=loggedin_user.first_name+ " "+loggedin_user.last_name%>
      <%= f.hidden_field :group_owner, :value => fullname%>
    </div>
  </div>
  <!-- <div class="field">
    <%= f.label :member1 %>(Optional)<br>
    <%= f.text_field :member1 %>
  </div>
  <div class="field">
    <%= f.label :member2 %>(Optional)<br>
    <%= f.text_field :member2 %>
  </div>
  <div class="field">
    <%= f.label :member3 %>(Optional)<br>
    <%= f.text_field :member3 %>
  </div>
  <div class="field">
    <%= f.label :member4 %>(Optional)<br>
    <%= f.text_field :member4 %>
  </div> -->
  <div class="form-group">
    <div class="field">
      <%= f.label :description, :class => "col-sm-2 control-label", :for =>"inputDescription"  %>
      <div class="col-sm-10">
        <%= f.text_area :description, :required=>'r', rows: "5", cols: "35", :class => "form-control", :id => "inputDescription"%>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="actions">
      <div class="col-sm-10 col-sm-offset-2">
        <%= f.submit :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>
<%end%>

app/views/groups/_form2.html.erb
<% if logged_in? %>
  <%= form_for(@group) do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
        <% @group.errors.full_messages.each do |message| %>
        <p style="text-align:left;"><%= message %></p>
        <% end %>
      </div>
    <% end %>
    <%if @group.member1id==nil%>
    <div class="field">
      <% fullname=loggedin_user.first_name+ " "+loggedin_user.last_name%>
      <%= f.hidden_field :member1, :value => fullname%>
      <%= f.hidden_field :member1id, :value => loggedin_user.id%>
    </div>
    <%elsif @group.member2id==nil%>
    <div class="field">
      <% fullname=loggedin_user.first_name+ " "+loggedin_user.last_name%>
      <%= f.hidden_field :member2, :value => fullname%>
      <%= f.hidden_field :member2id, :value => loggedin_user.id%>
    </div>
    <%elsif @group.member3id==nil%>
    <div class="field">
      <% fullname=loggedin_user.first_name+ " "+loggedin_user.last_name%>
      <%= f.hidden_field :member3, :value => fullname%>
      <%= f.hidden_field :member3id, :value => loggedin_user.id%>
    </div>
    <%elsif @group.member4id==nil%>
    <div class="field">
      <% fullname=loggedin_user.first_name+ " "+loggedin_user.last_name%>
      <%= f.hidden_field :member4, :value => fullname%>
      <%= f.hidden_field :member4id, :value => loggedin_user.id%>
    </div>
    <%end%>
    <div class="actions">
      <%= f.submit "join this group", :class => "btn btn-success "%>
    </div>
  <% end %>
<%end%>

app/views/groups/_form3.html.erb
<% if logged_in? %>
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <% @group.errors.full_messages.each do |message| %>
        <p style="text-align:left;"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <%if @group.member1id==loggedin_user.id%>
  <div class="field">
    <%= f.hidden_field :member1, :value => nil%>
    <%= f.hidden_field :member1id, :value => nil%>
  </div>
  <%elsif @group.member2id==loggedin_user.id%>
  <div class="field">
    <%= f.hidden_field :member2, :value => nil%>
    <%= f.hidden_field :member2id, :value => nil%>
  </div>
  <%elsif @group.member3id==loggedin_user.id%>
  <div class="field">
    <%= f.hidden_field :member3, :value => nil%>
    <%= f.hidden_field :member3id, :value => nil%>
  </div>
  <%elsif @group.member4id==loggedin_user.id%>
  <div class="field">
    <%= f.hidden_field :member4, :value => nil%>
    <%= f.hidden_field :member4id, :value => nil%>
  </div>
  <%end%>
  <div class="actions">
    <%= f.submit "Quit this group", :class => "btn btn-warning "%>
  </div>
<% end %>
<%end%>

app/views/groups/edit.html.erb
<% @page_title = "Groups-Edit" %>

<div class="groupEdit container">
  <div class="row">
    <div class="col-sm-12">
      <div class="col-sm-10">
        <% if logged_in? %>
          <% if loggedin_user.admin? || @group.user_id==loggedin_user.id%>
            <div class="form-horizontal">
              <fieldset>
                <legend><h3>Editing Gorup</h3></legend>
                <p>You are group owner, and you can edit this group</p>
                <%= render 'form' %>
               <!--  <%= link_to 'Show', @group, :class => "css_class"%>
                <%= link_to 'Back', groups_path, :class => "css_class"%> -->
              </fieldset>
            </div>
            <br>

          <%elsif @group.member1id==loggedin_user.id || @group.member2id==loggedin_user.id || @group.member3id==loggedin_user.id || @group.member4id==loggedin_user.id%>
            <div class="well">
              <p style="text-align:center;">Click "Quit this group" to Quit the "<%=@group.name%>" group</p>
            </div> 
            <%= render'form3' %>
            <br>

          <%elsif @group.member1id==nil || @group.member2id==nil || @group.member3id==nil || @group.member4id==nil%>
            <div class="well">
              <p style="text-align:center">Click "join this group" to finish joining "<%=@group.name%>" group</p>
            </div>
            <%= render'form2' %>
            <br>

          <%else%>
            <div class="well">
              <p style="text-algin:center"> This group is full</p>
            </div>
            <br>
          <%end%>

        <%else%>
          <div class="well">
            <p style="text-align:center"> Please log in before editing group</p>
          </div>
          <br>
        <%end%>
      </div>
      <div class="col-sm-2"></div>
    </div>
  </div>  <!-- end row -->
</div><!-- end groupEdit container -->

app/views/groups/index.html.erb
<% @page_title = "Groups" %>

<div class="groupIndex container">
 <!--  <p id="notice"><%= notice %></p> -->
  <h1>Here is all the groups, you can select the ones you like :p </h1>
  <p>Create your own gorup:<%= link_to ' New Group', new_group_path %></p>
  <br>
 
  <% @groups.each do |group| %>
    <% if group.activity_type== "study"%>
      <div class="row">
      <section class="col-xs-offset-3 col-xs-6 col-sm-offset-0 col-sm-6 col-md-4 col-lg-12">
        <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
            <img class="icon" src="assets/studyGroupSide.png" alt="Icon">
          </div>
          <div class="col-lg-1"></div>
          <div class="col-lg-9">
            <h3><%= group.name %></h3>
              <div class="row">
                <div class="col-lg-4 col-lg-offset-1">
                  <p>Activity time: <%= group.time %></p>
                </div>
                 <div class="col-lg-5 col-lg-offset-1">
                  <p>Location: <%= group.location %></p>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-4 col-lg-offset-1">
                  <p>Owner: <%= group.group_owner %></p>
                </div>
                 <div class="col-lg-5 col-lg-offset-1">
                  <p>Create time: <%= group.created_at%></p>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-11 col-lg-offset-1">
                  <p>Description: <%= group.description %></p>
                </div>
              </div>
              
              <div class="row">
                <div class="col-lg-7"></div>
                <div class="col-lg-5">
                  <%= link_to 'Show', group, :class => "btn btn-primary"%>
                  <% if logged_in?%>
                    <% if loggedin_user.admin? || group.user_id==loggedin_user.id%>
                      <%= link_to 'Edit the group', edit_group_path(group),:class => "btn btn-info" %>
                      <%= link_to 'Destroy', group,:class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                    <%elsif loggedin_user.id!=group.member1id && loggedin_user.id!=group.member2id && loggedin_user.id!=group.member3id &&loggedin_user.id!=group.member4id%>
                      <%if group.member1id==nil || group.member2id==nil || group.member3id==nil || group.member4id==nil%>
                        <%= link_to 'Join this group', edit_group_path(group), :class => "btn btn-success"%>
                      <%end%>
                    <%else%>
                      <%= link_to 'Quit this group', edit_group_path(group),:class => "btn btn-warning" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
          </div>
        </div>
      </section>  
    </div><!-- row end --> 
    <br>

    <% elsif group.activity_type== "sports"%>
      <div class="row">
      <section class="col-xs-offset-3 col-xs-6 col-sm-offset-0 col-sm-6 col-md-4 col-lg-12">
        <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
            <img class="icon" src="assets/sportGroupSide.png" alt="Icon">
          </div>
          <div class="col-lg-1"></div>
          <div class="col-lg-9">
            <h3><%= group.name %></h3>
              <div class="row">
                <div class="col-lg-4 col-lg-offset-1">
                  <p>Activity time: <%= group.time %></p>
                </div>
                 <div class="col-lg-5 col-lg-offset-1">
                  <p>Location: <%= group.location %></p>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-4 col-lg-offset-1">
                  <p>Owner: <%= group.group_owner %></p>
                </div>
                 <div class="col-lg-5 col-lg-offset-1">
                  <p>Create time: <%= group.created_at%></p>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-11 col-lg-offset-1">
                  <p>Description: <%= group.description %></p>
                </div>
              </div>
              
              <div class="row">
                <div class="col-lg-7"></div>
                <div class="col-lg-5">
                  <%= link_to 'Show', group, :class => "btn btn-primary"%>
                  <% if logged_in?%>
                    <% if loggedin_user.admin? || group.user_id==loggedin_user.id%>
                      <%= link_to 'Edit the group', edit_group_path(group),:class => "btn btn-info" %>
                      <%= link_to 'Destroy', group,:class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                    <%elsif loggedin_user.id!=group.member1id && loggedin_user.id!=group.member2id && loggedin_user.id!=group.member3id &&loggedin_user.id!=group.member4id%>
                      <%if group.member1id==nil || group.member2id==nil || group.member3id==nil || group.member4id==nil%>
                        <%= link_to 'Join this group', edit_group_path(group), :class => "btn btn-success"%>
                      <%end%>
                    <%else%>
                      <%= link_to 'Quit this group', edit_group_path(group),:class => "btn btn-warning" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
          </div>
        </div>
      </section>  
    </div><!-- row end --> 
    <br>

    <% elsif group.activity_type== "food"%>
      <div class="row">
      <section class="col-xs-offset-3 col-xs-6 col-sm-offset-0 col-sm-6 col-md-4 col-lg-12">
        <div class="row">
          <div class="col-lg-1 col-lg-offset-1">
            <img class="icon" src="assets/foodGroupSide.png" alt="Icon">
          </div>
          <div class="col-lg-1"></div>
          <div class="col-lg-9">
            <h3><%= group.name %></h3>
              <div class="row">
                <div class="col-lg-4 col-lg-offset-1">
                  <p>Activity time: <%= group.time %></p>
                </div>
                 <div class="col-lg-5 col-lg-offset-1">
                  <p>Location: <%= group.location %></p>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-4 col-lg-offset-1">
                  <p>Owner: <%= group.group_owner %></p>
                </div>
                 <div class="col-lg-5 col-lg-offset-1">
                  <p>Create time: <%= group.created_at%></p>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-11 col-lg-offset-1">
                  <p>Description: <%= group.description %></p>
                </div>
              </div>
              
              <div class="row">
                <div class="col-lg-7"></div>
                <div class="col-lg-5">
                  <%= link_to 'Show', group, :class => "btn btn-primary"%>
                  <% if logged_in?%>
                    <% if loggedin_user.admin? || group.user_id==loggedin_user.id%>
                      <%= link_to 'Edit the group', edit_group_path(group),:class => "btn btn-info" %>
                      <%= link_to 'Destroy', group,:class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                    <%elsif loggedin_user.id!=group.member1id && loggedin_user.id!=group.member2id && loggedin_user.id!=group.member3id &&loggedin_user.id!=group.member4id%>
                      <%if group.member1id==nil || group.member2id==nil || group.member3id==nil || group.member4id==nil%>
                        <%= link_to 'Join this group', edit_group_path(group), :class => "btn btn-success"%>
                      <%end%>
                    <%else%>
                      <%= link_to 'Quit this group', edit_group_path(group),:class => "btn btn-warning" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
          </div>
        </div>
      </section>  
    </div><!-- row end --> 
    <br>
    <% end %>

  <% end %>
</div><!-- groupIndex container end -->

app/views/groups/new.html.erb
<% @page_title = "Groups-Create" %>


<div class="groupCreate container">
  <div class="row">
    <div class="col-sm-12">
		<% if logged_in? %>

			<div class="form-horizontal">
				<fieldset>
				  <legend><h3>Create Gorup</h3></legend>
				  <%= render 'form' %>
				 <!--  <%= link_to 'Show', @group, :class => "css_class"%>
				  <%= link_to 'Back', groups_path, :class => "css_class"%> -->
				</fieldset>
			</div>
			<br>

		<% else %>
			<div class="well">
		    	<p style="text-align:center"> Please log in before creating group</p>
		    </div>
		    <br>
		<%end%>
    </div>
  </div>  <!-- end row -->
</div><!-- end groupCreate container -->

app/views/groups/show.html.erb
<% @page_title = "Groups-Show" %>


<div class="groupShow container">
  <div class="row">
    <div class="well col-sm-12">
      <h3>Welcome to the group "<%= @group.name %>"!<br></h3>

      <p>
        Owned by:
        <!-- <%= @group.group_owner %> -->
        <%= link_to @group.group_owner, @group.user, {:style=>'color:blue;', :class => "css_class"} %>
      </p>
      <p style="font-size:120%;">
        <br>
        This is a <%= @group.activity_type %> group.<br>
        Event will start at <%= @group.time %>  <br>
        Located at <%= @group.location %>.<br><br>
        Here is the description of this group:<br>
        <%= @group.description %>.
        <p>
          <% @user.each do |user| %>
            <%if user.id==@group.member1id%>
              Member1:
              <%= link_to @group.member1,user, {:style=>'color:blue;', :class => "css_class"} %>
            <%end%>
          <%end%>
        </p>

        <p>
          <% @user.each do |user| %>
            <%if user.id==@group.member2id%>
              Member2:
              <%= link_to @group.member2,user, {:style=>'color:blue;', :class => "css_class"} %>
            <%end%>
          <%end%>
        </p>

        <p>
          <% @user.each do |user| %>
            <%if user.id==@group.member3id%>
              Member3:
              <%= link_to @group.member3,user, {:style=>'color:blue;', :class => "css_class"} %>
            <%end%>
          <%end%>
        </p>

        <p>
          <% @user.each do |user| %>
            <%if user.id==@group.member4id%>
              Member4:
              <%= link_to @group.member4,user, {:style=>'color:blue;', :class => "css_class"} %>
            <%end%>
          <%end%>
        </p>
        <legend></legend>
      </p>

      <% if logged_in?%>
        <% if loggedin_user.admin? || @group.user_id==loggedin_user.id%>
          <%= link_to 'Edit', edit_group_path(@group), :class => "btn btn-primary" %> 
        <%elsif loggedin_user.id!=@group.member1id && loggedin_user.id!=@group.member2id && loggedin_user.id!=@group.member3id &&loggedin_user.id!=@group.member4id%>
          <%if @group.member1id==nil || @group.member2id==nil || @group.member3id==nil || @group.member4id==nil%>
            <%= link_to 'Join this group', edit_group_path(@group), :class => "btn btn-success " %>
          <%end%>
        <%else%>
          <%= link_to 'Quit this group', edit_group_path(@group), :class => "btn btn-warning "%>
        <%end%>
      <%end%>
    </div>
  </div>

  
  <script src="//maps.google.com/maps/api/js?key=AIzaSyCO3r_rsOGGXutONK6r1jsxsI6_1Fgn0xk"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- need custom infoboxes -->
  <div style='width: 100%;'>
    <div id="map" style='width: 100%; height: 400px;'></div>
  </div>
  <script type="text/javascript">
  setTimeout(function() {
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });

    //code for initializing the google map
  }, 700);
  </script><br><br><br>

  <div class="row">
    <div class="well col-sm-12">
      <legend><h2>Message</h2></legend>

      <p>
        <%= link_to 'Leave a message',new_message_board_path,  :class => "btn btn-primary"%>
      </p>

      <% @message_board.each do |message_board| %>
        <%if message_board.group_name==@group.name%>
        <div class="well">
          <p><b><%=message_board.sender%></b> left a message for this group:</p>
          <p style="text-indent: 7%;"><%= message_board.message%></p>
        </div>
        <%end%>
      <%end%>
    </div>
  </div>

  <br><br><br>
</div><!-- end groupCreate container -->