config/routes.rb
Rails.application.routes.draw do
  resources :ad_requests do
     member do
        get :delete
     end
 end
get 'ad_request/index'
  resources :message_boards
  get 'category/sports'

  get 'category/food'

  get 'category/study'

  get 'about_us/site_info'

  get 'about_us/contact'

  get 'about_us/FAQ'

  get 'sessions/new'

  resources :groups
  resources :users
  resources :widgets
  get  '/signup',  to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  root 'welcome#index'
  match ':controller(/:action(/:id))', :via=>[:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true) %>
    <!-- <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>s -->
    <!-- <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script> s -->
    <%= javascript_include_tag('application', 'data-turbolinks-track' => true) %>
    <%= csrf_meta_tags %>
    
    <!-- Optional IE8 Support -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <title>GroupIN | <%= @page_title || "Welcome" %></title>
  </head>
<body>
  <!-- Header -->
  <header class="">
    <!-- Navigation -->
    <nav class="navbar navbar-inverse">
      <div class="container">
        <!-- Brand and Hambuger collapsed -->
        <div class="navbar-header">
          <%= link_to("GroupIN",{:controller => 'welcome', :action => 'index'}, :class => 'navbar-brand')%>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsemenu" aria-expanded="false">
            <sapn class="sr-only">Toggle navigation</sapn>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- nav items -->
        <div class="collapse navbar-collapse" id="collapsemenu">
          <ul class="nav navbar-nav">
            <li><%= link_to("Home",{:controller => 'welcome', :action => 'index'}, :class => 'NavButtonL1')%></li>
            <li><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category<span class="caret"></sapn></a>
              <ul class="dropdown-menu">
                <li><%= link_to("ALL", groups_path, :class => "NavButtonL2") %></li>
                <li><%= link_to("Sports",{:controller => 'category', :action =>'sports'}, :class => 'NavButtonL2')%></li>
                <li><%= link_to("Food",{:controller =>'category', :action => 'food'}, :class => 'NavButtonL2')%></li>
                <li><%= link_to("Study",{:controller =>'category', :action => 'study'}, :class => 'NavButtonL2')%></li>
              </ul>
            </li>
            <li><%= link_to("Message Board",{:controller => 'message_boards', :action => 'index'}, :class => 'NavButtonL1')%></li>
            <% if logged_in? %>
              <%if loggedin_user.admin? %>
                <li><%= link_to("All Ad Requests",ad_requests_path, :class => 'NavButton1')%></li>
              <%else%>
                <li><%= link_to("New Ad Request",new_ad_request_path, :class => 'NavButton1')%></li>
              <%end%>
            <%else%>
              <li><%= link_to("Ad Request",new_ad_request_path, :class => 'NavButton1')%></li>
            <%end%>
            <li><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                About US<span class="caret"></sapn></a>
              <ul class="dropdown-menu">
                <li><%= link_to("Site Info",{:controller => 'about_us', :action =>'site_info'}, :class => 'NavButtonL1')%></li>
                <li><%= link_to("Contact",{:controller => 'about_us', :action =>'contact'}, :class => 'NavButtonL1')%></li>
                <li><%= link_to("FAQ",{:controller => 'about_us', :action =>'FAQ'},:class => 'NavButtonL1')%></li>
              </ul>
            </li> 
          </ul>
          <!-- Sign -->
          <% if logged_in? %>
          <!--   <button type="button" class="btn btn-default btn-xs navbar-btn navbar-right">
              <%= link_to("Log OUT", {:controller => 'sessions', :action => 'destroy'}, method: :delete, :class => 'Sign' )%>
            </button>
            <button type="button" class="btn btn-default btn-xs navbar-btn navbar-right">
              <%= link_to("Profile", user_path(loggedin_user), :class => 'Sign' )%>
            </button> -->
            <p class="navbar-text navbar-right">
              <%= link_to("Log OUT", {:controller => 'sessions', :action => 'destroy'}, method: :delete, :class => 'Sign' )%>
            </p>
            <p class="navbar-text navbar-right">
              <%= link_to("Profile", user_path(loggedin_user), :class => 'Sign' )%>
            </p>
             <%if loggedin_user.admin? %>
              <P class="navbar-text navbar-right">logged in as admin</p>
            <%else%>
              <P class="navbar-text navbar-right">logged in as <%= loggedin_user.email%><p>
            <%end%>
          <% else %>
            <!-- <button type="button" class="btn btn-default btn-xs navbar-btn navbar-right">
              <%= link_to("Sign UP",{:controller => 'users', :action => 'new'}, :class => 'Sign')%>
            </button>
            <button type="button" class="btn btn-default btn-xs navbar-btn navbar-right">
              <%= link_to("Log IN",{:controller => 'sessions', :action => 'new'}, :class => 'Sign')%>
            </button> -->
            <p class="navbar-text navbar-right">
              <%= link_to("Sign UP",{:controller => 'users', :action => 'new'}, :class => 'Sign')%>
            </p>
            <p class="navbar-text navbar-right">
              <%= link_to("Log IN",{:controller => 'sessions', :action => 'new'}, :class => 'Sign')%>
            </p>
          <% end %>
          <!-- search bar -->
          <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
              <%= link_to("search", {:controller => 'search', :action => 'index'},:class => "btn btn-default" )%>
          </form>
        </div><!-- end of nav item and for collapsed-->

      </div>  <!-- end of nav container-->
    </nav>
  </header>



  <!-- Main -->
  <div id="main">
    <% if !flash[:notice].blank? %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <div id="WelcomeContent">
      <%= yield %>
    </div><!-- WelcomeContent end -->

  </div><!-- main end -->

  <!-- Footer -->
  <footer class="Bottom">
    <div class="container">
      <address id="copyright"><br>&copy; Simon Fraser University | CMPT276 Group15</address>
    </div>
  </footer>
</body>

</html>